name: rx_scan
description: A prescription scanner that syncs to google calendar

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  
  survey_kit: ^0.1.1
  edge_detection: ^1.1.3
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  provider: ^6.0.0
  rflutter_alert: ^2.0.7
  async: ^2.11.0
  http: ^1.1.0
  auth0_flutter: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
